### ISSUE TITLE
Request for new error code from "RST399 Undefined substitution referenced"

### ISSUE THREAD

**Issue by bskinn** [peterjc/flake8-rst-docstrings#10]
RST allows definition of ["substitution sequences"](http://docutils.sourceforge.net/docs/ref/rst/restructuredtext.html#substitution-definitions):

```
Here's where the |foo| substitution is used.

.. |foo| replace:: Here's where it's defined.

```

When using Sphinx, I put commonly used substitution sequences into [`rst_epilog` in my `conf.py`](https://github.com/bskinn/sphobjinv/blob/94e705e62409e0359c1f6eb7897dd52e6c363d96/doc/source/conf.py#L129-L211). When running `flake8-rst-docstrings`, this leads to the per-file RST not knowing about these `conf.py`-defined substitutions, and so I get, e.g., from [this line](https://github.com/bskinn/sphobjinv/blob/94e705e62409e0359c1f6eb7897dd52e6c363d96/tests/test_api_fail.py#L4):

```
tests\test_api_good.py:4:1: RST399 Undefined substitution referenced: "objects.inv".
Sphinx |objects.inv| files.
```

It would be good to assign this error its own code, so that I can selectively ignore them.

**Comment by peterjc** [comment]
+1

That seems clear, thank you for another concise report. I've never used substitutions, so this RST feature is new to me.

If you want to implement this yourself, I'd welcome a pull request - but otherwise I should be able to tackle that this week.

**Comment by bskinn** [comment]
Happy to tag them in myself! I do have some thoughts on #7 / #8; I'll post them at #8 when I get a chance.
