### ISSUE TITLE
Reading from a closed stdin buffer error

### ISSUE THREAD

**Issue by sobolevn** [peterjc/flake8-rst-docstrings#19]
Original issue: https://github.com/wemake-services/wemake-python-styleguide/issues/871

# Bug report

## What's wrong

Opening a file in emacs+flycheck just raises `ValueError: I/O operation on closed file`.
Though it's not an issue with WPS, but with some flake8 plugins, I want this to get off from the ground somehow.

Plugins that are responsible for that:

- [x] flake8-bandit (I already had made a [PR](https://github.com/tylerwince/flake8-bandit/pull/14) and it was merged)
- [x] flake8-print (https://github.com/JBKahn/flake8-print/pull/36)
- [x] flake8-debugger (https://github.com/JBKahn/flake8-debugger/issues/18)
- [ ] flake8-rst-docstrings (There are no issues or pr regarding that yet.)

You can dive deeper into the topic by reading flake8-print PR. 
To be able to use WPS now -- I should firstly uninstall those plugins, that's a pain.

## How is that should be

It should work without errors :)

**Comment by peterjc** [comment]
Do you have a standalone test case?

**Comment by sobolevn** [comment]
Nope 😢

**Comment by peterjc** [comment]
This works for me (example on some of the linked issues), but perhaps the version of flake8 is important too?

```
$ flake8 --version
3.7.9 (black: 0.1.1, flake8-blind-except: 0.1.1, flake8-bugbear: 19.8.0, flake8-comprehensions: 3.0.1, flake8-docstrings: 1.5.0, pydocstyle: 4.0.1, flake8_quotes: 2.1.0, mccabe: 0.6.1, pycodestyle: 2.5.0, pyflakes: 2.1.1, rst-docstrings: 0.0.12) CPython 3.7.4 on Darwin
$ python -m flake8 - < path/to/python/file.py
...
```

What version of flake8 do you have?

**Comment by sobolevn** [comment]
I guess that @nndii (from https://github.com/wemake-services/wemake-python-styleguide/issues/871) can help with the original versions. 

But, PR from https://github.com/JBKahn/flake8-print/pull/36 shows that `flake8` version is `3.7.6`

**Comment by peterjc** [comment]
Nope, no exception with flake 3.7.6 either - when mine is the only plugin:

```
$ python -m flake8 --version
3.7.6 (mccabe: 0.6.1, pycodestyle: 2.5.0, pyflakes: 2.1.1) CPython 3.7.3 on Linux
$ python -m flake8 - < ~/repositories/flake8-rst-docstrings/setup.py
stdin:41:80: E501 line too long (83 > 79 characters)
```

It is the combination of plugins that seems important, e.g.

```
$ python -m flake8 --version
3.7.6 (flake8-print: 3.1.0, mccabe: 0.6.1, pycodestyle: 2.5.0, pyflakes: 2.1.1, rst-docstrings: 0.0.11) CPython 3.7.3 on Linux
$ python -m flake8 - < repositories/flake8-rst-docstrings/setup.py
stdin:0:1: RST900 Failed to load file: I/O operation on closed file
stdin:41:80: E501 line too long (83 > 79 characters)
```

Upgrading ``flake-print`` and the problem goes away:

```
$ python -m flake8 --version
3.7.6 (flake8-print: 3.1.4, mccabe: 0.6.1, pycodestyle: 2.5.0, pyflakes: 2.1.1, rst-docstrings: 0.0.11) CPython 3.7.3 on Linux
$ python -m flake8 - < repositories/flake8-rst-docstrings/setup.py
stdin:41:80: E501 line too long (83 > 79 characters)
```

Likewise,

```
$ python -m flake8 --version
3.7.6 (flake8-tuple: 0.2.13, mccabe: 0.6.1, pycodestyle: 2.5.0, pyflakes: 2.1.1, rst-docstrings: 0.0.11) CPython 3.7.3 on Linux
$ python -m flake8 - < repositories/flake8-rst-docstrings/setup.py
stdin:0:1: RST900 Failed to load file: I/O operation on closed file
stdin:41:80: E501 line too long (83 > 79 characters)
```

Upgrading ``flake8-tuple`` again the problem goes away:

```
$ python -m flake8 --version
3.7.6 (flake8-tuple: 0.4.0, mccabe: 0.6.1, pycodestyle: 2.5.0, pyflakes: 2.1.1, rst-docstrings: 0.0.11) CPython 3.7.3 on Linux
$ python -m flake8 - < repositories/flake8-rst-docstrings/setup.py
stdin:41:80: E501 line too long (83 > 79 characters)
```

I strongly suspect that the ``RST900 Failed to load file: I/O operation on closed file`` error from my plugin is a side effect of the monkey patching triggered in the older versions of ``flake-print`` and ``flake8-tuple`` (especially as I don't explicitly use the ``get_stdin_value`` call).

If you upgrade ``flake-print`` and ``flake8-tuple`` does the problem go away?

**Comment by nndii** [comment]
Yes, actually I had upgraded WPS and it's working now

**Comment by peterjc** [comment]
Thanks for confirming, I'm closing this issue now.
