### ISSUE TITLE
Not working for for file with shebang line

### ISSUE THREAD

**Issue by IngoHeimbach** [peterjc/flake8-rst-docstrings#2]
Hey,
I have tested your extension and I find it very useful. Unfortunately, it does not work for files with shebang lines, for example:
```python
#!/usr/bin/env python
# -*- coding: utf-8 -*-
```
The error message is:
```
RST901: Failed to parse file: encoding declaration in Unicode string
```

**Comment by peterjc** [comment]
Thank you for the report - the first from an end user which is extra special 🥇 

Unfortunately I can't reproduce it - could you confirm which version of the plugin you have via ``flake8 --version`` please, e.g.

```
$ more hello_world.py 
#!/usr/bin/env python
# -*- coding: utf-8 -*-
print("Hello world")

$ flake8 hello_world.py 
hello_world.py:1:1: D100 Missing docstring in public module

$ flake8 --version
3.4.1 (flake8-blind-except: 0.1.1, flake8-docstrings: 1.1.0, pydocstyle: 2.0.0, flake8_commas._base: 0.4.3, mccabe: 0.6.1, pycodestyle: 2.3.1, pyflakes: 1.5.0, radon: 2.0.2, rst-docstrings: 0.0.5) CPython 3.6.0 on Darwin
```

The error you report is referring to the PEP263 https://www.python.org/dev/peps/pep-0263/ style unicode declaration on line two, not the shebang itself on line one.

I'm hoping you're using an older release, and updating to rst-docstrings 0.0.5 will fix this -  that was specifically to tackle this kind of problem.

**Comment by IngoHeimbach** [comment]
Thanks for your fast reply. :)
I am using the latest version:
```
$ flake8 --version
3.4.1 (flake8-docstrings: 1.1.0, pydocstyle: 2.0.0, mccabe: 0.6.1, pycodestyle: 2.3.1, pyflakes: 1.5.0, rst-docstrings: 0.0.5) CPython 2.7.13 on Darwin
```
Oddly enough, your sample code also fails for me. I get the same error code as before (`RST901`).

**Comment by peterjc** [comment]
Thank you - I see you're using flake8 under Python 2.7 while just now I tested flake8 under Python 3.6 -- that was what I was missing.

I can now reproduce this on macOS by explicitly controlling which Python and flake8 is run:

```
$ python -m flake8 --version
3.4.1 (mccabe: 0.6.1, pycodestyle: 2.3.1, pyflakes: 1.5.0, rst-docstrings: 0.0.5) CPython 2.7.10 on Darwin
```

```
$ python -m flake8 hello_world.py 
hello_world.py:0:1: RST901 Failed to parse file: encoding declaration in Unicode string (hello_world.py, line 0)
```

I really ought to set aside time for a proper test suite (#3), but now that I can at least explore what is wrong here since we have a simple test case 👍

**Comment by peterjc** [comment]
It looks like this was a bug in my backport of ``tokenize.open`` for the corner case where the PEP263 encoding was on line two (as happens with a hashbang on line one).

Could you update to 0.0.6 (live on PyPI) and re-test please? I've run this locally against the Biopython project without problems - and the new test case passes.

**Comment by peterjc** [comment]
Leaving issue open pending confirmation from @IngoHeimbach that v0.0.6 fixed things.

**Comment by IngoHeimbach** [comment]
Tested it, works for me like a charm! Thank you very much 👍

**Comment by peterjc** [comment]
Great - thanks for taking the time to report this and re-test.
