### ISSUE TITLE
RST299 Cannot analyze code. Pygments package not found.

### ISSUE THREAD

**Issue by peterjc** [peterjc/flake8-rst-docstrings#20]
Not sure if this deserves its own error code. Probably should just declare pygments an explicit requirement?

**Comment by caioariede** [comment]
Related issue: https://github.com/twolfson/restructuredtext-lint/issues/41

**Comment by caioariede** [comment]
@peterjc yes, I think that would be a good addition

**Comment by peterjc** [comment]
This will be in the next release, v0.1.0, which also drops Python 2 support.

**Comment by peterjc** [comment]
Correction, this was in v0.1.1
