### ISSUE TITLE
Add test cases for python3.7 and python3.8

### ISSUE THREAD

**Issue by sobolevn** [peterjc/flake8-rst-docstrings#21]
Currently both `tox.ini` and `travis.yml` do not support latest python versions.

I can send a PR with the fix! 

Related: https://github.com/wemake-services/wemake-python-styleguide/issues/1138

**Comment by peterjc** [comment]
Good point.

TravisCI is easy, done in https://github.com/peterjc/flake8-rst-docstrings/commit/3651dae12baf7629b216a08b09197f9f3ff1929e https://travis-ci.org/peterjc/flake8-rst-docstrings/builds/659820837

When you said tox were you looking at another project?

**Comment by sobolevn** [comment]
Yeap, yours does not have `tox`! Thanks a lot.

**Comment by peterjc** [comment]
Thanks
