### ISSUE TITLE
Plugin should use lines (or tree), provided by flake8

### ISSUE THREAD

**Issue by skirpichev** [peterjc/flake8-rst-docstrings#25]
It seems, this plugin uses a hackish way to parse files by itself, instead of using provided by flake8 infrastructure.  This is much like https://github.com/zheller/flake8-quotes/issues/93.  I believe, it's easy to fix too.

**Comment by peterjc** [comment]
I agree - this plugin is a great big hack to glue docutils docutils into flake8.

If you know lots about AST, you could be very well placed to clean this up. If you want to work on this, I would be happy to look at a pull request.

**Comment by domdfcoding** [comment]
From what I can tell (having used AST very briefly yesterday), the docstring is stored as an  `ast.Expr` object in the "body" of an `ast.FunctionDef` object representing the function. Classes are presumably represented differently in the AST.

From the `ast.Expr` object the following can be accessed:

- the docstring text, via the `.value.s` attribute
- the lineno, via the `.lineno` attribute
- the col_offset, the the `.col_offset` attribute

I've put together[ a rough example](https://gist.github.com/domdfcoding/63d69230339b6cbe9eebb4201b3db694) of how to extract the docstrings from an AST, modelled after Anthony Sottile's flake8_2020 plugin, so I assume this is the correct way to do it. I imagine this could then be passed to docutils for it to do its thing?

I'll try and explore this further over the weekend.

**Comment by peterjc** [comment]
That sounds very promising @domdfcoding 👍

**Comment by peterjc** [comment]
Pull request #33 will clean this up a lot but just importing the pydocstyle parser, but does not address this point directly: We still reparse the Python file when flake8 already did it and can share the AST.

**Comment by peterjc** [comment]
I made some time to look at this today, what do you think of the code on PR #35 using the AST?

**Comment by skirpichev** [comment]
Looks good.  I've noticed some workarounds for ancient python versions.  Maybe it's time to drop this?

**Comment by peterjc** [comment]
Yeah, the workaround for Python 3.3 and 3.4 was trivial though, so I decided to leave it in for now. I'm expecting and hoping no one complains about my dropping Python 2.7 support yesterday.

**Comment by peterjc** [comment]
Closed by #35 and the release of v0.2.0, thank you for the suggestion.
