### ISSUE TITLE
Unknown directive type

### ISSUE THREAD

**Issue by ubmarco** [peterjc/flake8-rst-docstrings#4]
Hello,
I'm using the [sphinxcontrib-needs](http://sphinxcontrib-needs.readthedocs.io/en/latest/) extension. It brings own Sphinx directives flake8-rst-docstrings does not know about. For example, my test cases have docstrings containing a new test directive `.. test:: Test invalid build spec`.
So I get errors like
```
./tests/application/test_cli/test_cli.py:6:1: RST399 Unknown directive type "test".
./tests/application/test_input/test_input.py:9:1: RST399 Unknown directive type "test".
```
What are my best chances to get around this issue? Is there a configuration option to add my custom directives? Or do I have to ignore those lines or ignore RST399 completely? The documentation tells me `RST399 | Previously unseen major error, not yet assigned a unique code.` - I think it makes sense to have RST399 enabled if some other unseen major error shows up.

Thanks
  Marco

**Comment by peterjc** [comment]
Can you provide a complete (short) Python file using the test directive, which could become a test case?

I'd probably define a new ``RST303`` code for ``Unknown directive type``, which would cover any unknown directive (not just ``test``). However, this will need a slight refactoring of the code as thus far everything has been an exact string match. You could then ignore ``RST303``.

(There could be an endless list of possible directives, so trying to assign a unique code for each of them seems a bad idea.)

Does this sound sensible?

**Comment by peterjc** [comment]
Ha - there is even a TODO in the code for this, so I must have had a failing example myself once...

https://github.com/peterjc/flake8-rst-docstrings/blob/v0.0.7/flake8_rst_docstrings.py#L193

**Comment by ubmarco** [comment]
Thanks for the immediate feedback. Yes, ignoring a new error code `RST303` would be an option. Another approach would be to add a user configuration parameter which extends the list of allowed directives. This would avoid the error messages but would still be sensible regarding other directives that shall really not be used or just don't exist.

Here's a short example Python file:
```
from cmimporter.applications.cmimporter_app.cmimporter_app import CmImporter

def test_import_app():
    """
    .. test:: Initialisation of CMImporter
        :id: TC_CMI_001
        :tags: cmimporter

        * Checks if the app can be instantiated.
    """
    app = CmImporter()
    assert app is not None
```
However, the there may also be more fields like `:status:`, it depends on the configuration of the sphinxcontrib-needs extension.

**Comment by peterjc** [comment]
I'm trying using this example http://sphinxcontrib-needs.readthedocs.io/en/latest/examples.html#examples from as a new test file ``tests/test_cases/sphinx-needs.py``,

```rst
**Some data**

.. req:: My first requirement
   :id: req_001
   :tags: example

   This is an awesome requirement and it includes a nice title,
   a given id, a tag and this text as description.

.. spec:: Spec for a requirement
   :links: req_001
   :status: done
   :tags: important; example

   We haven't set an **ID** here, so sphinxcontrib-needs
   will generated one for us.

   But we have **set a link** to our first requirement and
   also a *status* is given.

**Some text**

Wohooo, we have created :need:`req_001`,
which is linked by :need_incoming:`req_001`.

**A filter**

.. needfilter::
   :tags: example
   :layout: table
```

```
$ flake8 --select RST tests/test_cases/*.py
tests/test_cases/sphinx-needs.py:8:1: RST399 Unknown directive type "req".
tests/test_cases/sphinx-needs.py:15:1: RST399 Unknown directive type "spec".
tests/test_cases/sphinx-needs.py:28:1: RST399 Unknown interpreted text role "need".
tests/test_cases/sphinx-needs.py:28:1: RST399 Unknown interpreted text role "need_incoming".
tests/test_cases/sphinx-needs.py:33:1: RST399 Unknown directive type "needfilter".
```

So we'll probably define ``RST304 Unknown interpreted text role`` as well.

**Comment by ubmarco** [comment]
Yes, true, there are additional roles. I think passing specific IDs makes total sense.
What do you think about my proposal to make additional directives and roles configurable?

**Comment by peterjc** [comment]
I've not yet had to work out how a flake8 plugin does configuration, but if you wanted to work on it - sure. You'd like lists of "allowed" directives and roles which would be ignored for these new error conditions?

**Comment by peterjc** [comment]
Are you able to test the code in 4726c9aeba1faab88f79fb877a3c4c4ea6289d28 on pull request #5, which could be v.0.0.8 but is not yet on the master branch nor on PyPI?

**Comment by ubmarco** [comment]
Thanks for the PR. I'll test it today.

Adding configuration to flake8 plugins is described [here](http://flake8.pycqa.org/en/latest/plugin-development/plugin-parameters.html#registering-options) and [here](http://flake8.pycqa.org/en/latest/plugin-development/cross-compatibility.html#parsing-options-from-configuration-files).

**Comment by ubmarco** [comment]
I tested it right now and it worked.

- I observed an ID change from RST399 to RST303 for the message 'Unknown directive type'.
- I observed an ID change from RST399 to RST304 for the message 'Unknown interpreted text role'.

**Comment by peterjc** [comment]
Thanks for testing - I'll merge that pull request and push the release to PyPI today.

I'm pretty sure that my problem with using ``# noqa`` while testing this is a flake8 issue, logged as https://gitlab.com/pycqa/flake8/issues/375

**Comment by peterjc** [comment]
@ubmarco thank you for your feedback and quick testing. Plugin v0.0.8 with this work is now on PyPI.

Feel free to open an enhancement issue for user-defined directives for use with ``RST303`` etc.

**Comment by ubmarco** [comment]
Thanks for the release and for your time. I'll investigate if the solution is enough. If I need the enhancement, I'll open another issue and send you the PR.
