### ISSUE TITLE
Add support for signature overloading

### ISSUE THREAD

**Issue by xmo-odoo** [peterjc/flake8-rst-docstrings#46]
Sphinx' `autodoc` supports the ability to overload signatures, which is useful for expressing e.g. semantics which older versions of Python don't support (like positional-only arguments in code compatible with pre-3.8).

However currently this is checked like "normal" rst code and thus any signature which looks a bit like invalid rST will trigger an error e.g.
```python
def foo(*args, **kwargs):
    """foo([thing, ][**params]) -> Thing
    """
```
Furthermore it is *not* possible to "escape" the signature, sphinx will fail to interpret a `literal` as a signature, and it will not apply regular escapes (backslashes) leading to incorrect rendering of the sig'.

**Comment by peterjc** [comment]
Can you point me at the relevant Sphinx documentation for this?

Do you think always ignore these lines is sensible? Or might it be better configurable (some people will not be using Sphinx)?

**Comment by xmo-odoo** [comment]
> Can you point me at the relevant Sphinx documentation for this?

Sure, it's controlled by [`autodoc_docstring_signature`](https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html#confval-autodoc_docstring_signature). Note that while the documentation for this setting mentions C function it applies to every function, or method, or class.

The exact check seems to be [`py_ext_sig_re`](https://github.com/sphinx-doc/sphinx/blob/fe47bf46cbb6a615b01d6c5dc9fdcac58c940f69/sphinx/ext/autodoc/__init__.py#L51-L59). This feature seems to be specifically handled in the [`DocstringSignatureMixin`](https://github.com/sphinx-doc/sphinx/blob/fe47bf46cbb6a615b01d6c5dc9fdcac58c940f69/sphinx/ext/autodoc/__init__.py#L1177-L1181), which is used for `FunctionDocumenter`, `ClassDocumenter`, and `MethodDocumenter`; as well as `DocstringStripSignatureMixin` which is used for `AttributeDocumenter` and `PropertyDocumenter` but seems a lot less relevant (it seems to be used to... discard an explicit signature for attributes / properties?)

> Do you think always ignoring these lines is sensible? Or might it be better configurable (some people will not be using Sphinx)?

Might be useful to always avoid checking such lines, even if people don't use sphinx a line which looks like a python signature probably should not be checked? e.g.cpython itself uses this docstring style even though it does not use autodoc:

- [`textwrap.TextWrapper.wrap` source](https://github.com/python/cpython/blob/3.10/Lib/textwrap.py#L350)
- [`textwrap.TextWrapper.wrap` documentation](https://docs.python.org/3/library/textwrap.html#textwrap.TextWrapper.wrap)

The docstring is extensive and uses a signature-style first line, but it's completely replaced for the actual documentation.

**Comment by peterjc** [comment]
```python
#: extended signature RE: with explicit module name separated by ::
py_ext_sig_re = re.compile(
    r'''^ ([\w.]+::)?            # explicit module name
          ([\w.]+\.)?            # module and/or class name(s)
          (\w+)  \s*             # thing name
          (?: \((.*)\)           # optional: arguments
           (?:\s* -> \s* (.*))?  #           return annotation
          )? $                   # and nothing more
          ''', re.VERBOSE)
```

So we could perhaps try importing ``py_ext_sig_re`` from Sphinx, failing that default on the current regular expression - and try matching it to each docstring. We'd then want to ignore it (noting the offset for RST error line numbers). That seems doable.

Do you want to try working on this? I'd be happy to review a pull request.

**Comment by xmo-odoo** [comment]
> So we could perhaps try importing `py_ext_sig_re` from Sphinx, failing that default on the current regular expression - and try matching it to each docstring.

So kind of an optional dependency on sphinx, use it in case it's installed under the assumption that it's probably being used?

**Comment by xmo-odoo** [comment]
Incidentally, just to be sure: the validity of info fields (aside from basic syntactic stuff) is out of scope for this checker correct?

**Comment by peterjc** [comment]
There is something to be said for just hard coding the regular expression, but yes - I was thinking:

```python
try:
    from sphinx.ext.autodoc import py_ext_sig_re
except ImportError:
    py_ext_sig_re = re.compile(
        r'''^ ([\w.]+::)?            # explicit module name
              ([\w.]+\.)?            # module and/or class name(s)
              (\w+)  \s*             # thing name
              (?: \((.*)\)           # optional: arguments
               (?:\s* -> \s* (.*))?  #           return annotation
              )? $                   # and nothing more
              ''', re.VERBOSE)
```

And yes, I would regard the validity of this signature as out of scope for ``flake8-rst-docstrings``.

**Comment by xmo-odoo** [comment]
> There is something to be said for just hard coding the regular expression, but yes - I was thinking:
> 
> ```python
> try:
>     from sphinx.ext.autodoc import py_ext_sig_re
> except ImportError:
>     py_ext_sig_re = re.compile(
>         r'''^ ([\w.]+::)?            # explicit module name
>               ([\w.]+\.)?            # module and/or class name(s)
>               (\w+)  \s*             # thing name
>               (?: \((.*)\)           # optional: arguments
>                (?:\s* -> \s* (.*))?  #           return annotation
>               )? $                   # and nothing more
>               ''', re.VERBOSE)
> ```

Seems fair, maybe with a note indicating which version the regex got lifted from.
 
> And yes, I would regard the validity of this signature as out of scope for `flake8-rst-docstrings`.

I was thinking more about the info fields like `:param:` and friends, in $dayjob's codebase I've found that a lot of colleagues screw up on those e.g. a bunch of then are written `:param varname type:` or somesuch.

**Comment by peterjc** [comment]
Oh right. Again, that feels out of scope... worth asking if ``docstrings`` (and thus ``flake8-docstrings``) would tackle it?

**Comment by xmo-odoo** [comment]
Guessing you mean pydocstyle? I'll go check if they're concerned by info fields. Thanks.
