### ISSUE TITLE
Multiple-letter violation codes are not displayed by Vim Syntastic syntax checker

### ISSUE THREAD

**Issue by myii** [peterjc/flake8-rst-docstrings#6]
**This is not a bug with your plugin** but I'm raising this here for your awareness, since you use multiple-letter violation code(s).

I've filed an issue with `vim-syntastic`: https://github.com/vim-syntastic/syntastic/issues/2163.

The resolution of that bug may be of interest to you.  If not, please disregard this report, with my apologies.

**Comment by peterjc** [comment]
Thanks for the heads up - I personally don't use vim so hadn't run into this. See also https://gitlab.com/pycqa/flake8/issues/339 for better documenting the prefix recommendations for flake8 plugin authors.

**Comment by myii** [comment]
@peterjc You're welcome.  Appreciate your plugin, by the way.

> See also https://gitlab.com/pycqa/flake8/issues/339 for better documenting the prefix recommendations for flake8 plugin authors.

Brilliant, this is one of the resources that I couldn't track down when I was discussing violation code clashes recently @ https://github.com/PyCQA/flake8-bugbear/issues/37.

> > Peter Cock @pjacock commented 9 months ago
> > 
> > I've opened #339 looking at the prefix conventions and improving the plugin development documentation about this.
> > 
> > Given since v3.0 Flake8 isn't restricted to 4 character long violation codes, I like your suggestion of using RST as the prefix here.
> 
> ...
> 
> * At some point, **I came across another discussion, that was very much in favour of using longer prefixes**, since there aren't enough to go around all of the plugins that are now available -- unfortunately, I don't have time to track that down right now

* That's quite a lengthy conversation there but it leads to a lot of overlap with https://gitlab.com/pycqa/flake8/issues/339 -- including extracting a number of existing violation code ranges out there in the wild
* In fact, it even ends up with GitLab MR, doing precisely what you are suggesting at the end of your issue
* I've just gone ahead and linked those up already @ https://gitlab.com/pycqa/flake8/merge_requests/229

**Comment by myii** [comment]
The Syntastic issue has been resolved so I'll close this issue, too.

**Comment by peterjc** [comment]
Thanks for your efforts - future vim users' lives should be a little smoother now.

**Comment by myii** [comment]
@peterjc I didn't do anything spectacular.  It's all about the developers and maintainers, that's where the real credit is due.
