### ISSUE TITLE
Bug with single word on first line of docstring

### ISSUE THREAD

**Issue by jhpalmieri** [peterjc/flake8-rst-docstrings#65]
I think that the line

https://github.com/peterjc/flake8-rst-docstrings/blob/3551caf4c2270a24fa4b87d4a4fb0d22be746111/flake8_rst_docstrings.py#L200

should be changed to include a count of 1:

`docstring = docstring.replace(firstline, "") -> docstring = docstring.replace(firstline, "", 1)`

Otherwise it replaces other instances of `firstline` in the whole string. In SageMath, for example, the first line of a docstring might be "Axioms", and then any line starting with "Axioms " get changed to start with the trailing space " ", at which point the parser thinks the line is indented.

**Comment by mkoeppe** [comment]
Test case: https://trac.sagemath.org/ticket/34168#comment:18

**Comment by peterjc** [comment]
Fixed in v0.2.7, thanks all!

https://pypi.org/project/flake8-rst-docstrings/0.2.7/
