### ISSUE TITLE
Request for new error code from "RST399 Unknown target name"

### ISSUE THREAD

**Issue by bskinn** [peterjc/flake8-rst-docstrings#9]
RST allows definition of [hyperlink references](http://docutils.sourceforge.net/docs/ref/rst/restructuredtext.html#hyperlink-targets):

```
Here's where the hyperlink-name_ is used.

.. _hyperlink-name: Here's where the hyperlink target is defined.

```

When using Sphinx, I put commonly used hyperlink targets into [`rst_epilog` in my `conf.py`](https://github.com/bskinn/sphobjinv/blob/94e705e62409e0359c1f6eb7897dd52e6c363d96/doc/source/conf.py#L129-L211). When running `flake8-rst-docstrings`, this leads to RST not knowing about these `conf.py`-defined targets, and I get, e.g., from [this line](https://github.com/bskinn/sphobjinv/blob/94e705e62409e0359c1f6eb7897dd52e6c363d96/tests/test_api_fail.py#L22):

```
tests\test_api_good.py:23:1: RST399 Unknown target name: "license_txt".
```

It would be good to assign this error its own code, so that I can selectively ignore them.

**Comment by peterjc** [comment]
+1

That seems clear, thank you for a concise report.

If you want to implement this yourself, I'd welcome a pull request - but otherwise I should be able to tackle that this week.
